Cardinal-Entertainment/Cryptoz.cards-Dapp

- src/components/OwnedCardContent.vue
> show spinner when sacrificing in progress

- src/components/OwnerBalances.vue
> Set subscriptions on mount

- src/components/CryptContent.vue
- src/components/HelpContent.vue
- src/components/OwnedCardContent.vue
- src/components/ShopContent.vue
- src/util/showToast.js
Lots of reformatting. But the main changes are inside `ShopContent.getAllTypes`. 
Also removed watch on `totalCyptozTypes` because we only need to refetch all cards on mount. 
Also fixed help section
> disable button if card is owned in shop

- src/App.vue
- src/components/CryptContent.vue
- src/components/OwnedCardContent.vue
- src/components/ShopContent.vue
- src/components/SortDropdown.vue
- src/helpers.js
Summary of changes:
- Add table view to the crypt with a toggle button
- Moved buttons out of OwnedCardContent and into ShopContent and CryptContent
- Improved gift modal
- Moved gift modal out of OwnedCardContent into CryptContent
- Made helpers.js for common functions
- Went ham on dynamicSort instead of just cleaning the data as it came in from backend
- Made SortDropdown.vue component with button for toggling ascending/descending
- Turned "Sacrifice" button into skull and crossbones emoji
> Add table view in Your Crypt

- src/components/CryptContent.vue
> Validate wager amount on FE

- src/components/OwnerBalances.vue
- src/components/ShopContent.vue
- src/components/layout/AppHeader.vue
- src/router/index.js
- src/store/index.js
This will close the 2nd part of issue #32 . The first part is already resolved in a previous PR
> Mutate the ether balance in header after booster purchase

- package.json
- src/components/CryptContent.vue
- src/components/layout/AppHeader.vue
- src/main.js
- src/util/addressUtil.js
- yarn.lock
A lot of changes are formatting changes. 
Change:
- Added sponsor link on header if connected with Metamask
- Able to copy own sponsor link as `url?sponsor=0x3u...`
- If never linked, there will be an input with link button to add a sponsor
- Once linked, should not be able to link again
- If goes to an url with `?sponsor=...` present, will open the modal on loaded with input filled in (if connected)
> add sponsor modal

- src/components/layout/AppHeader.vue
lol I was sending all sponsors to your address @ryanprice
> Prevent user from linking their own address

- src/components/ShopContent.vue
Closes #37 
No real magic here, let me know if you think there is a more efficient way to hit this, otherwise lock er down
> query typeToEdition and display on card in Shop

- src/components/ShopContent.vue
Adding new fetch logic to shop.
> fetch json for shop also

- src/components/HelpContent.vue
- src/components/ShopContent.vue
Fix:
- fetch json in shop
- Changed help h1 to `Frequently Asked Questions`
> small fixes

- src/components/ShopContent.vue
Shop updates
set limit to match chain on card 19
added 4 new card types ready for Test
gwei to 30 on the test net.. geez
> hack for card19 and Next 4 shop cards

- src/components/ShopContent.vue
I wont deploy to main until approval and merge
> 6 card types added for TestNEt RC

- src/components/CryptContent.vue
- src/components/OwnerBalances.vue
- src/components/UniverseBalances.vue
- src/components/layout/AppHeader.vue
> app header mobile responsive

- src/components/MarketContent.vue
- src/components/ShopContent.vue
- src/components/layout/AppHeader.vue
Affiliate modal text changes
Store text changes
re-enabled pancake swap
re-enabled shop booster button tooltip
> Text changes

- src/components/BodyContent.vue
- src/components/ShopContent.vue
change ERC-20 to BEP-20
removed an extra space in the text in shop
> Fixed the token type on body

- src/App.vue
- src/components/CardsContainer.vue
- src/components/CryptContent.vue
- src/components/OthersCryptContent.vue
- src/components/SortDropdown.vue
- src/router/index.js
This PR is for implmeneting see another person's crypt:
- user can click a button to get own crypt link
- user can search for another person's crypt
- user can go back to my own crypt 
Notes:
- `CardsContainer` is basically a copy of CryptContent, which can be used to refactor later on
- CryptContent changes include a lot of formatting, oops about that, I suggest just play with the feature and try to break it
> allow seeing another person's crypt

- src/components/CardsContainer.vue
- src/components/CryptContent.vue
- src/components/OthersCryptContent.vue
> display address label

- src/components/CardsContainer.vue
- src/components/CryptContent.vue
- src/components/HelpContent.vue
- src/components/OthersCryptContent.vue
- src/components/ShopContent.vue
- src/components/layout/AppHeader.vue
- src/router/index.js
Updated all the references to /crypt with /my-cryptoz-nfts
( I think ) !
> Updated link to Google friendly nft crypt

- src/components/CardsContainer.vue
- src/components/CryptContent.vue
- src/components/OthersCryptContent.vue
Card container is now used as a child component for both crypt content and other's crypt content. 
Work done:
- Cleaned up code and removed duplicate get card actions
- sacrifice and gift won't reload all cards
- Added pending toasts and confirmation toasts to all contract actions
- my crypt + others crypt mobile ready
There shouldn't be any changes in the app. If everything "works", then PR works.
> refactor crypt content and lots of clean up

- src/components/ShopContent.vue
> New shop types available on Testbsc to test

- src/components/ShopContent.vue
> Added store types back in and, sold for limit bug on 2 cards

- src/components/ShopContent.vue
> disable mint button after user click

- src/components/CardsContainer.vue
a small PR for adding clear sort for crypt component
> clear sorting for crypt

- src/components/MarketContent.vue
- src/components/layout/AppHeader.vue
Not sure why it's complaining , I tried to clean it up
> broken by linter

- src/components/ShopContent.vue
Fix done:
- importing error toast since we are using it
- Removed useless imports
- modify booster modal so it looks nice
> make booster modal look better, fix error toast bug

- src/App.vue
- src/components/CardsContainer.vue
- src/components/CryptContent.vue
- src/components/CryptTable.vue
- src/components/ShopContent.vue
- src/store/cardStore.js
- src/store/cryptStore.js
- src/store/index.js
- Refactored table into its own component. (prop easier for infinite scroll this way)
- Created a new store for crypt related actions: load crypt cards, get more, sacrifice, gift, open boosters
- Infinite scroll on crypt cards view, but load more for table view (@jjjhill help pls)
I think this will need extensive testing
> pagination on crypt page + refactoring states

- src/store/cardStore.js
> New store card, more to come

- src/store/cardStore.js
> gaga going up

- src/components/MarketContent.vue
make market look cleaner and mobile responsive.
> rework market

- src/components/CryptContent.vue
Hey guys, can I get help with making this display better on different size displays
thanks !
> Booster mint probs

- src/components/CardsContainer.vue
- src/store/cryptStore.js
found a small bug, for crypt that don't have any NFTs we displayed an infinite spinner with a console error
> fix small bug in displaying no cards

- src/components/DataIndicators.vue
- Added Diamond
- Adjusted existing doughnut graphs for new type
- Added new doughnut for All minted by Rarity called from chain
> Nft rarity indicator

- src/store/cardStore.js
> 1 card added to store

- src/App.vue
- src/components/CardsContainer.vue
- src/components/CryptContent.vue
- src/components/SortDropdown.vue
- src/store/cryptStore.js
Need a thorough test with this one.
> Filter store by booster vs store

- README.md
- src/components/HelpContent.vue
some wording changes in help section and add CZXP to metamask button added
> New add CZXP to metamask button

- src/components/CryptContent.vue
- src/components/SortDropdown.vue
> wager-percent-tooltip-and-sort-by-date-released

- src/App.vue
Show a modal when cannot detect web3 from the browser. We can work on the text/styling afterwards
> show a modal when cannot detect web3

- src/components/layout/AppHeader.vue
> add telegram share link

- src/components/CardsContainer.vue
- src/components/CryptContent.vue
- src/components/CryptTable.vue
- src/components/OwnedCardContent.vue
- src/components/SortDropdown.vue
- src/store/cryptStore.js
- src/store/state.js
> mass sac and sorting dropdown changes

- src/components/CardsContainer.vue
- src/components/CryptContent.vue
- src/components/OwnedCardContent.vue
- src/components/TokenContent.vue
- src/components/layout/AppHeader.vue
update all the urls to also consider moonbase.zoombie.world
> update urls to include moonbase.zoombies

- src/components/ShopContent.vue
- src/components/layout/CzxpRewardEffect.vue
Feel free to suggest some better ways to do this 👍
> Shop css buttons

- src/App.vue
- src/components/BodyContent.vue
- src/components/layout/Header.vue
- src/main.css
- src/main.js
New homepage with zoom count, nft count, static player count and splash image
> New homepage

- src/components/CardSets.vue
- src/components/CardsContainer.vue
- src/components/EventNotification.vue
- src/components/RealtimeEvents.vue
- src/store/blockChainStore.js
- src/store/cardStore.js
- src/store/cryptStore.js
- src/util/cardUtil.js
- src/util/watcherUtil.js
watch transfer event. 
Only show message if from and to are not zero addresses.
> watch transfer event for gifting

- package.json
- src/components/TokenContent.vue
- src/store/cardStore.js
- yarn.lock
All functional except the radial, left in placeholder mode. 
Looking to push this to moonbase for early feedback
Any suggestions on optimization ? functionality ?
> View card NFT details

- src/App.vue
- src/components/CardSets.vue
- src/components/OwnedCardContent.vue
- src/store/blockChainStore.js
- src/store/cryptStore.js
check the subgraph for card types that have been minted
place a banner on cards that have never been minted
banner on card types you own and not owned
> Sets owned status

- src/components/CardSets.vue
- src/components/OwnedCardContent.vue
- src/store/cardsetStore.js
- src/store/index.js
- src/util/cardUtil.js
> filtering cardsets

- src/store/cardsetStore.js
- src/util/cardUtil.js
a little manually done, feel free to improve to make it more dynamic
> removed console and requested 600 rows for card sets

- package.json
- src/components/CardsContainer.vue
- src/components/CryptContent.vue
- src/store/blockChainStore.js
- yarn.lock
I am sure could use a tidy or better way to implement. feel free to change
Tested and working
> added gas estimates and limits to calls

- .eslintrc.js
- src/components/BodyContent.vue
- src/components/DataIndicators.vue
- src/components/HelpContent.vue
- src/components/ShopContent.vue
- src/components/SortDropdown.vue
- src/components/TokenContent.vue
- src/components/layout/AppFooter.vue
- src/util/bodyUtil.js
all placeholders
we are going after this
> New zoombies dashboard

- node_scripts/getSVGtoPNG.js
- package.json
Add getSVGtoPNG.js to convert svg to png.
> Add getSVGtoPNG script

- src/components/BodyContent.vue
Stop timer when component unmounted.
> Stop timer when component unmounted

- src/components/layout/Header.vue
> Change label to Connect
